package ch.heigvd.dai.commands;

enum ServerCommand {
    ID_ASSIGN,
    NAME_VALIDATED,
    LOBBY_STATE,
    GAME_STATE,
    CARD_PLAYED,
    VICTORY,
    DEFEAT,
    RESET_ISSUED,
    STATUS_UPDATE_READY,
    STATUS_UPDATE_UNREADY,
    WARNING_COMMAND_INVALID,
    WARNING_NAME_MID_SESSION,
    WARNING_NAME_WITH_READY,
    WARNING_NAME_TAKEN,
    WARNING_ALREADY_READY,
    WARNING_ALREADY_NOT_READY,
    WARNING_GAME_NOT_STARTED,
    WARNING_DECK_EMPTY,
    WARNING_CARD_NOMATCH,
    WARNING_CARD_SYNTAX,
    WARNING_CARD_COOLDOWN,
    ERROR_LOBBY_FULL,
    ERROR_FATAL,
    CLOSE_CONNECTION,
    PLACEHOLDER
}