package ch.heigvd.dai.commands;

enum ServerCommand {
    NAME_VALIDATED,
    GAME_STATE,
    VICTORY,
    DEFEAT,
    STATUS_UPDATE_READY,
    STATUS_UPDATE_UNREADY,
    WARNING_COMMAND_INVALID,
    WARNING_CANT_NAME_WHEN_READY,
    WARNING_NAME_TAKEN,
    WARNING_GAME_NOT_STARTED,
    WARNING_CARD_NOMATCH,
    WARNING_CARD_COOLDOWN,
    ERROR_LOBBY_FULL,
    ERROR_FATAL,
    PLACEHOLDER
}