package ch.heigvd.dai.commands;

enum ServerCommand {
    ASSIGN_ID,
    NAME_VALIDATED,
    GAME_STATE,
    CARD_PLAYED,
    VICTORY,
    DEFEAT,
    STATUS_UPDATE_READY,
    STATUS_UPDATE_UNREADY,
    WARNING_COMMAND_INVALID,
    WARNING_NAME_WITH_READY,
    WARNING_NAME_TAKEN,
    WARNING_GAME_NOT_STARTED,
    WARNING_DECK_EMPTY,
    WARNING_CARD_NOMATCH,
//    WARNING_CARD_MISSING_VALUE,
    WARNING_CARD_SYNTAX,
    WARNING_CARD_COOLDOWN,
    ERROR_LOBBY_FULL,
    ERROR_FATAL,
    PLACEHOLDER
}